services:
  web:
    build:
      context: .
      dockerfile: build.Dockerfile
    restart: unless-stopped
    networks:
      - app-network

  proxy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
