services:
  app:
    image: node:24
    container_name: server
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8000"
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
      interval: 5s
      retries: 10
    build:
      context: .
      dockerfile: server.Dockerfile
networks:
  default:
