services:
  app:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: server
    restart: always
    ports:
      - "80:8080"
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
      interval: 5s
      retries: 10
    working_dir: /home/node/app
    volumes:
      - ./app:./
      - ./views:./views
    depends_on:
      - db
  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: test
    restart: always
    command: sh -c "npm install && npm test"
    depends_on:
      - app
  db:
    image: postgres:latest
    restart: always
    shm_size: 512mb
    env_file: ./.env
networks:
  default:
